### ISSUE TITLE
Product Feedback Process

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#107]
This issue is to drive the creation of a detailed process to obtain user feedback on products posted on the Hub

**Comment by ckoroma** [comment]
I say we test the PDF and see how that goes, if we have an uptick in traffic or feedback that indicates users hate that process we can reconsider another option like the .md, thoughts?

**Comment by jonmost** [comment]
Agree



Sent with Good (www.good.com)


-----Original Message-----

**Comment by aaronpava** [comment]
I posted a Contribute process here: https://github.com/usds/techfar-hub

Does this resolve this ticket?
