### ISSUE TITLE
Add Lean Canvas

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#108]
Per our conversation at the team meeting, @shannonsartin would drop the lean canvas in the assets/files folder and provide a brief description. Additional content will be provided later (maybe a video).

**Comment by TraciLW** [comment]
It has updates to it that need to be made before dropping it in

**Comment by jonmost** [comment]
If we know what they are can we do them?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by shannonsartin** [comment]
@TraciLW  do you mean the changes based on feedback from the class? or changes we discussed before? 

maybe we could sprint on this next week for an hour or so if it is the latter?

**Comment by jonmost** [comment]
@TraciLW @shannonsartin Where are we with this?

**Comment by shannonsartin** [comment]
@jonmost unsure .. waiting for @TraciLW ill corner her tomorrow and get an answer

**Comment by ckoroma** [comment]
Circling back on this, there is a note in the issues to add lean canvas to techfar. Is this one of which you are speaking?

[Lean_Acquisition_Canvas.pptx](https://github.com/usds/techfar-hub/files/781273/Lean_Acquisition_Canvas.pptx)

**Comment by ben-USDS-damman** [comment]
This has been open too long. Closing to move the conversation to usds/techfar-hub-v2#17
