### ISSUE TITLE
VA Case Study

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#109]
Per our staff meeting @brentmar was going to work on getting a case study from Mark for the HUb. When you have it you can drop it in the Asset/file folder and let Clair and I know

**Comment by jonmost** [comment]
@TraciLW @brentmar Per the deep dive, I take it that Traci has a plan for this? What is the timeline on this?

**Comment by ckoroma** [comment]
Case study was completed and submitted to @TraciLW and @brentmar
