### ISSUE TITLE
Send Contribute button to .MD file

### ISSUE THREAD

**Issue by TraciLW** [usds/techfar-hub#120]
When people click Contribute- they should be sent to the "code" page with the instructional .md file and not "Issues" because of the new instructions we put there- for those unfamiliar with Github - directing putting people into the "issues" Page might be confusing. @jonmost @aaronpava

**Comment by aaronpava** [comment]
@TraciLW Are you referring to the text and button on https://techfarhub.cio.gov/contribute/ ? You want them to be sent to this page instead: https://github.com/usds/techfar-hub ?

cc: @jonmost
