### ISSUE TITLE
sharing analytics with the team

### ISSUE THREAD

**Issue by shannonsartin** [usds/techfar-hub#124]
@TraciLW @aaronpava @ckoroma @jonmost @brentmar would you like to see analytics from the site on a regular basis? any specific cadence requested? 

thinking we should get this set up, just want to make sure it is meaningful and not done just for the sake of doing it.

**Comment by brentmar** [comment]
I think this would be valuable

**Comment by jonmost** [comment]
Yes!



Sent with Good (www.good.com)


-----Original Message-----

**Comment by aaronpava** [comment]
@shannonsartin Yes, perhaps Monthly.

**Comment by ckoroma** [comment]
monthly please

**Comment by jonmost** [comment]
@shannonsartin can this be closed?

**Comment by shannonsartin** [comment]
no, leaving this open. sent follow up email on how to to get access to analytics account. 

plan is for @aaronpava to get access, set up analytics to be circulated to our team on a monthly basis

@jonmost should also get access for when @aaronpava is not online

we can close once those things are done

**Comment by aaronpava** [comment]
I have requested access. For reference (and what Jon-a-than may also want to do):

1. Go to https://accounts.google.com/NewAccount an add gov email address. Make sure to click the "I prefer to use my current email address" link under the "Choose a username" input field and enter your agency email address there. Do not create a new gmail.com address. 

2. Send an email to support.digitalgov.gov titled "Requesting Analytics access"
 
Hello,

I was unable to access the DAP User Registration Form so here is the necessary information:

Aaron Pava
Aaron_S_Pava@omb.eop.gov
Agency: OMB/EOP
Website: https://techfarhub.cio.gov/
Employee Status: Federal Employee

I agree to the terms of the DAP User Agreement.

I have associated my .gov email with Google Analytics.

Thanks so much!
Aaron

**Comment by rebelwarrior** [comment]
I requested access to the Agile Solicitation Builder's stats the same way Pava did yesterday. Got an email saying they're having trouble with the Analytics. @aaronpava did your request go through?

**Comment by parismartin** [comment]
@rebelwarrior @shannonsartin hey - did either of you ever get access to analytics for TechFar Hub or Solicitation builder? thanks!

**Comment by shannonsartin** [comment]
@parismartin @rebelwarrior there is a monthly email with analytics that comes out to the techfarhub distro

do you want me to forward to you?

**Comment by TraciLW** [comment]
@shannonsartin i forwarded it- and I have asked 18F for the analytics on Solicitation builder- need this anyway for our hosting requirements.

**Comment by rebel-one** [comment]
@shannonsartin new user name @rebel-one. I was in the process of getting the analytics but haven't looked at that since I've been out of the project.

**Comment by ckoroma** [comment]
https://github.com/usds/procurement/blob/master/TechFAR-Hub/TFanalytics/readme.md
