### ISSUE TITLE
creating engagement options

### ISSUE THREAD

**Issue by shannonsartin** [usds/techfar-hub#125]
we need an additional engagement tool, past stackexchange for people to learn more about things we are working on

most likely a general techfarhub listserv. thoughts?

**Comment by aaronpava** [comment]
Agreed. Is there already a pre-existing listserv that we could make announcements on? Or would the techfarhub listserv users be unique? (DITAP participants, Procureminati, etc.)

**Comment by jonmost** [comment]
There is the old buyers club listserv that ursula took over. Don't think we should make a new one unless we think there is a unique need (possibly one that includes industry would be a good reason)

**Comment by shannonsartin** [comment]
I would be curious to know if from a branding perspective we want to create a new one. I know it is obnoxious to be subscribed to a ton of listservs, but it seems important to have something that someone could use to sign up for more. Buyers club might work, but it feels like since it was a pre-exisitng effort it might not be the right option? unsure..

**Comment by rebelwarrior** [comment]
@aaronpava @jonmost @shannonsartin What's the state of this?

**Comment by ckoroma** [comment]
We created the DITAP listserv, others are possible depending on how and what we want to communicate.  We also have a pseudo list serv of vendors who attend our industry days, as in I send them emails.
