### ISSUE TITLE
Serving the local site

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#130]
@cew821 I am trying to serve the Jekyll local version on my computer and getting a message "command not found" is the gemfile working for you?

**Comment by cew821** [comment]
When you run `$ jekyll -v` what do you get?

**Comment by jonmost** [comment]
command not found

**Comment by jonmost** [comment]
I am using my DoD laptop, maybe I need to install Jekyll

**Comment by cew821** [comment]
Yes it sounds like Jekyll is not installed. If you have ruby (test by running  `$ ruby -v` and you should see 2.x.x), then navigate to the directory where you have the project downloaded and run `$ bundle install` -- that will download and install all of the ruby packages the site needs, including Jekyll.

If you don't have ruby, probably easiest to ask an engineer on your team the way they recommend ruby installs on the their team (but feel free to reach out if you need help)!

**Comment by rebelwarrior** [comment]
If you are installing a gem on a work computer you might need to change the target for ruby gems in the gem file from https to plain http.

@jonmost If Charles solved your problem can we close this issue?
