### ISSUE TITLE
Design / Front End Needs 

### ISSUE THREAD

**Issue by mebates** [usds/techfar-hub#227]
# USDS'ers on the call
Lauren - Interaction and Visual Design
Andrew L-B - Interaction, Design Research, unreliable Front End Code ;)
Kat - Design research, IA, Content-related stuff
Jeff - Research and design, not visual 
Laura - Research, prototyping
Mollie - Interaction and visual design, interested in research
Clair - Design and code, SME on Aquitisions team
David - Product Strat Ops, coder

# TechFAR Hub Needs
## User Research #228 
* Needs to happen before the rest
* Identify list of users - experienced CO, inexperienced CO, 
* Qualitative interviews
* Take a look at analytics

## New IA
* Test with users

## New site design
* Homepage
* Align with USDS and USWDS
* Want to use the landing page template: https://standards.usa.gov/page-templates/#landing-page

## Report templates
* For PDFs on site 

# Solicitation Builder
## User Research #231 
* Will ask general questions in site redesign research
* Not ready for development yet
* Ready for ideas and story boarding

Who's going to do what? How much time do you have to do it?

**Comment by lkadamus** [comment]
I'm happy to work on the user research, new IA and site design. I think that we can get started on the IA with after doing only 1 or 2 user interviews by relying on best practices and from there focus on validating that our assumptions work for our users. That might help us move forward if scheduling with users is difficult.

**Comment by ckoroma** [comment]
Moving to readme of the discovery
