### ISSUE TITLE
User Research for Site Redesign

### ISSUE THREAD

**Issue by ckoroma** [usds/techfar-hub#228]
**Comments**
* Needs to happen before the rest
* Project for this task is: https://github.com/usds/techfar-hub/projects/1

**Tasks**
*What Problem is this site solving? (Types of topics for which Users would come to TechFar)
  * Other resources are mostly unknown, google is probably the main tool used
  * Tools to build agile solicitations and determine the costs 
   * Why would you use this tool?

* Identify list of users
  * experienced CO
  * inexperienced CO
  * COR
  * PM or Program Manager
  * vendors
  * Fed gov partners in acquisition community (e.g. DHS, SBA, CMS, OFPP)
* Qualitative interviews: Interview various stakeholders about their experience using techfarhub
  * CO: Jennifer Johnson (Jennifer.Johnson@dot.gov)
  * CO and owner: Jonathan Mostowski(jmostowski@omb.eop.gov)
  * CO and DHS partner: Erica Evans(erica.evans@dhs.hq.gov)
  * COR and DHS partner: Mike Palmer(michael.palmer@hq.dhs.gov)
  * Vendor: Roderick Avery(ra@integrityunitedtechnologies.com)
  * Vendor: Lloyd Tang(lloyd.tang@tea-llc.com)
  * Vendor: Anil Patibandla(Anil.patibandla@c-mci.com)
  * Vendor: Riley Skanes(riley@skanestech.com)
  * Fedgov partner, SBA: Amber Sierra(amber.seira@sba.gov)
  * DITAP cohort 2 participants: https://github.com/usds/procurement/blob/master/TechFAR-Hub/AgileSolicitationBuilder/ListOfUsers.md(https://github.com/usds/procurement/blob/master/TechFAR-Hub/AgileSolicitationBuilder/ListOfUsers.md)
* Take a look at analytics: *See* [TechFarHub Analytics Folder](https://github.com/usds/techfar-hub/tree/master/TFanalytics)

**Comment by parismartin** [comment]
@ckoroma hey quick question Fedgov partner, SBA: Amber Sierra(amber.seira@sba.gov) do you know which way her last name is spelled? I don't want to bounce the email I'm sending. Thanks!
