### ISSUE TITLE
User Research for Solicitation Tool Redesign

### ISSUE THREAD

**Issue by ckoroma** [usds/techfar-hub#231]
Notes and discussion on users for solicitation tool.

## User List
Users who can be interviewed re use of the solicitation tool.

**Comment by ckoroma** [comment]
@rebelwarrior please document all all those who responded to your call to action for the solicitation tool during the last DITAP training under "User List" for the issue.  We will need name, email and phone if possible

**Comment by rebelwarrior** [comment]
I've added the list to Github, names and emails. 
procurement/TechFAR-Hub/AgileSolicitationBuilder/ListOfUsers.md

**Comment by rebelwarrior** [comment]
@ckoroma added telephone numbers as well, anything else or should I close?

**Comment by ckoroma** [comment]
This is great @rebelwarrior.  Working on reorging material then will close issue.
