### ISSUE TITLE
Interview Guide

### ISSUE THREAD

**Issue by mebates** [usds/techfar-hub#236]
Hey @lkadamus - some feedback on your [Interview Guide](https://github.com/usds/techfar-hub/blob/master/Redesign_ReDev/Discovery/interview-guide.md); keeping it here so all can see!

> 
> Are you familiar with the Federal Acquisition Regulation (FAR)?
> 
> Has it changed the way you procure technology services?
> How? (looking to validate that FAR provides CO with more flexibility to conduct acquisitions in innovative ways)

Do you mean to say the 'TechFAR' here? The FAR is the set of regulations that help COs do their job; all will be *very* familiar with the FAR. They may not know about the 'TechFAR'; defined as - "Another tool is the TechFAR, which highlights flexibilities [2] in the Federal Acquisition Regulation (FAR [3]) that can help agencies implement “plays” in the Playbook that would be accomplished with acquisition support."

I think it's confusing that we have a thing called "TechFAR"; "TechFAR Handbook" and "TechFAR Hub". What are all these things, and how are they different? Is this a term that only USDS uses; do other COs even know about it? cc: @ckoroma 

Some alternative questions:

- Have you heard of the TechFAR Handbook? Or the TechFAR Hub? 
- If so, have these resources changed the way you procure technology services?
- How? 
- If they haven't heard of it -- How would you figure out how to procure Agile software development services within the bounds of the FAR? or something like that

Did we also want to include some broad questions about the Solicitation Tool?

**Comment by mebates** [comment]
cc: @JeffBarnesUSDS and @readywater. We'd love your feedback and help with recruiting, scheduling, and conducting interviews this week!

**Comment by lkadamus** [comment]
@mebates that's a really good point. 

For the Solicitation tool do you want to ask some questions like:
Have you used the Solicitation Tool on the TechFAR hub to build a solicitation? 
(If yes) What was that experience like? How did it differ from the way you normally do solicitations? What worked well? What didn't? 
(If no) Can you tell me about how you usually create a solicitation? What are some common challenges you face building solicitations? 

I just sent out a bunch of outreach emails to schedule interviews for early next week. I'll be out Wed - Friday of this week.
