### ISSUE TITLE
Typos in AIA List

### ISSUE THREAD

**Issue by oghaffari** [usds/techfar-hub#288]
https://github.com/usds/techfar-hub/blob/323156f314a60909ce82df04d59ac576009c4bbd/initiatives/AIAlist.md

----

> Department of Transportation: Darbi Dillon, Associate Director, Acquisition Policy Oversight/Business Strategy,`( `Darbi.Dillon@dot.gov](Darbi.Dillon@dot.gov), 202-366-3300

should be

> Department of Transportation: Darbi Dillon, Associate Director, Acquisition Policy Oversight/Business Strategy,` [`Darbi.Dillon@dot.gov](Darbi.Dillon@dot.gov), 202-366-3300

----

> Dave Zvenyach, Acquisition Management Director, 18F: `(`Vladlen.Zvenyach@gsa.gov](Vladlen.Zvenyach@gsa.gov), 202-676-6512

should be

> Dave Zvenyach, Acquisition Management Director, 18F: `[`Vladlen.Zvenyach@gsa.gov](Vladlen.Zvenyach@gsa.gov), 202-676-6512

----

> NASA: Bill McNally, Senior Procurement Executive, [William.P.Mcnally@nasa.gov](William.P.Mcnally@nasa.gov`]`

should be

> NASA: Bill McNally, Senior Procurement Executive, [William.P.Mcnally@nasa.gov](William.P.Mcnally@nasa.gov`)`

----

> Social Security Administration: Randy Pickwell, Senior Technical Advisor (experienced CO and former OAG Division Director),`( `Randall.Pickwell@ssa.gov]( Randall.Pickwell@ssa.gov), 410-966-1325

should be

> Social Security Administration: Randy Pickwell, Senior Technical Advisor (experienced CO and former OAG Division Director),` [`Randall.Pickwell@ssa.gov]( Randall.Pickwell@ssa.gov), 410-966-1325

----

> AIA Council Liaisons`LIAISONS-`

should be

> AIA Council Liaisons

----

> Defense Innovation Unit Experimental (DIUx): Lauren Schmidt, Pathways Director, [Lauren@diux.mil]`]`(Lauren@diux.mil), 570-594-2204

should be

> Defense Innovation Unit Experimental (DIUx): Lauren Schmidt, Pathways Director, [Lauren@diux.mil](Lauren@diux.mil), 570-594-2204

----

> Prizes and Challenges: Kelly Olson, Senior Innovation Advisor, [Kelly.Olson@gsa.gov](Kelly.Olson@gsa.gov`]` or `(`Team@challenge.gov](Team@challenge.gov), 202-297-4522

should be

> Prizes and Challenges: Kelly Olson, Senior Innovation Advisor, [Kelly.Olson@gsa.gov](Kelly.Olson@gsa.gov`)` or `[`Team@challenge.gov](Team@challenge.gov), 202-297-4522

**Comment by TraciLW** [comment]
Thank you for the feedback - we will get it corrected

**Comment by ckoroma** [comment]
@oghaffari we launched a new site and the new list is located here: https://techfarhub.cio.gov/initiatives/aia-list/

Thank you for your feedback.
