### ISSUE TITLE
Text on "About" button on home page not visible

### ISSUE THREAD

**Issue by billy22g** [usds/techfar-hub#289]
<img width="359" alt="screen shot 2017-11-03 at 1 50 59 pm" src="https://user-images.githubusercontent.com/5091167/32393163-1f01fa10-c09e-11e7-9a74-47ef12b03dd5.png">

**Comment by jas298** [comment]
@TraciLW This one is for you!

**Comment by TraciLW** [comment]
@ckoroma @JeffBarnesUSDS @nacin assigning the bug to Jeff but anyone can fix it. Thanks

**Comment by ckoroma** [comment]
@billy22g this issue is resolved.  Thank you for the feedback.
