### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#46]
Add analytics to techfarhub site, or discuss what is involved; low priority until we have an official launch date

**Comment by cew821** [comment]
I have added the google analytics code to master, so it should feed this to the digital analytics program once it's deployed to github pages

**Comment by jonmost** [comment]
@cew821 how do I get credentials or access to view the analytics?

**Comment by cew821** [comment]
You will need to create a google account using your .gov email address. Go here: https://accounts.google.com/signup and be sure to select "use my current email address" 

I'm asking what the next step is, I think you have to get added to the access list but i'm not sure.

**Comment by cew821** [comment]
Here are the current stats, if you're interested: 

![image](https://cloud.githubusercontent.com/assets/1237498/17254967/015762c8-5585-11e6-8592-972aaee3c63c.png)

**Comment by jonmost** [comment]
Thanks!
