### ISSUE TITLE
Limit Line length

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#72]
@cew821 I can't figure out how to limit the line length for the unstructured list (the rest of the site follows the design standards line containment). Can you take a look. When I did it in the jonmost version I wrote CSS to contain each type (headings, paragraphs, etc.., not sure how to do it in the structure.

**Comment by jonmost** [comment]
The CSS shows 
".usa-content-list {
  max-width: 53rem; }" 
which should contain it, but doesn't seem to be applying

**Comment by cew821** [comment]
@jonmost this is done in master, I'll leave it to you to deploy to gh-pages
