### ISSUE TITLE
Agile Estimator

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#78]
@cew821 currently the "Agile Estimator" on the Do IT page is an excel document hosted on heroku, owned by Julia Win (no longer Government). I can't remember exactly why we did it that way, but now it limits my ability to make changes. Any thoughts on a good workaround?

For what it is, it may be as simple as just adding it to the assets and linking to the document internally, open to suggestions.

**Comment by cew821** [comment]
Hi @jonmost, yes this should be as simple as adding the file to our assets folder and linking to it internally.

**Comment by jonmost** [comment]
Replaced file, issue appears resolved
