### ISSUE TITLE
Problem with Downloads

### ISSUE THREAD

**Issue by cew821** [usds/techfar-hub#81]
The following downloads do not work: 

## In Templates...
- [Statement of Objectives Template](/assets/files/DigitalServiceSOO.docx)
- [Agile Task Order FFP Independent Government Cost Estimate (IGCE) Template Example](/assets/files/Agile_Task_Order_IGCE_Example_-Sec_508_Remediated.docx)

## In Samples
- [Request For Quotes System Modernization Sample](/assets/files/Agile%20Task%20Order%20Example.docx)
- [Request For Quote Enterprise Collaboration and Customer Relationship Management Correspondence System Implementation](/assets/files/CRMTaskOrder%20Sample%20DRAFT.docx)

**Comment by cew821** [comment]
I think we need to re-upload different files to the file folder, ideally without spaces in their names. We should ensure they can be opened on windows machines before uploading them. We should also consider if PDFs would be more appropriate.

**Comment by cew821** [comment]
I am temporarily removing links to the broken files in production.

**Comment by jonmost** [comment]
Okay, I think word docs are better since the intention is that they will be used. I recognize the problem if you don't have word though. Open to suggestions, i would like to fix this today

**Comment by jonmost** [comment]
@cew821 second problem, I can't seem to locate the original documents for any of these

**Comment by jonmost** [comment]
@cew821 all documents are replaced, links restored, testing complete, all open successfully, thanks for the help!
