### ISSUE TITLE
Review and add case studies

### ISSUE THREAD

**Issue by jonmost** [usds/techfar-hub#91]
@jonmost We talked at GoodGovUX about examples of case studies from some work we've done at the FTC.

18F recently wrote a case-study-esque blog post about the redesign of identitytheft.gov. I didn't work on the redesign, but can put you in touch with my colleagues who did.

A few years ago we redesigned our main consumer site. This redesign involved changing our content strategy to writing for digital first.

tpeeler@ftc.gov

**Comment by ckoroma** [comment]
In progress
